---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-generic
  namespace: nvidia-gpu-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-generic
rules:
- apiGroups:
  - machine.openshift.io
  resources:
  - machinesets
  verbs:
  - '*'
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  verbs:
  - '*'
- apiGroups:
  - autoscaling.openshift.io
  resources:
  - machineautoscalers
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - secrets
  resourceNames:
  - aws-creds
  verbs:
  - get
  - list
# - nonResourceURLs:
#   - '*'
#   verbs:
#   - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-generic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-generic
subjects:
  - kind: ServiceAccount
    name: job-generic
    namespace: nvidia-gpu-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-generic-
  name: job-generic
  namespace: nvidia-gpu-operator
  # annotations:
  #   argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: job-generic
          # image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          image: registry.redhat.io/openshift4/ose-cli
          env:
            - name: INSTANCE_TYPE
              value: "g4dn.4xlarge"
            - name: AWS_REGION
              value: "us-east-1"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/bash
            - -c
            - /scripts/job.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: job-generic
            defaultMode: 0755
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: job-generic
      serviceAccountName: job-generic