apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-pvc
  namespace: openwebui
  labels:
    app: openwebui
    app.kubernetes.io/component: openwebui
    app.kubernetes.io/instance: openwebui
    app.kubernetes.io/name: openwebui
    app.kubernetes.io/part-of: openwebui
    component: openwebui
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi