apiVersion: v1
kind: Namespace
metadata:
  name: demo-project
  annotations:
    openshift.io/description: |
      Demo project for notebooks and model serving
    openshift.io/display-name: demo-project