apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
stringData:
  htpasswd: |
    admin:$2y$05$We0TGIGGHYUsPp0K8xY1COwLA2OiZ07VAxE8x4edy4rSq4/1FeRwi