apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  htpasswd: |
    {{ .Values.admin.username }}:{{ .Values.admin.passwordHash }}

