- name: Taint GPU nodes for NVIDIA GPU workloads
  hosts: localhost
  vars:
    repo_dir: "{{ lookup('env', 'REPO_DIR') | default(playbook_dir | dirname | dirname, true) }}"
  tasks:
    - name: Get GPU nodes with nvidia.com/gpu.present=true label
      shell: |
        oc get nodes -l nvidia.com/gpu.present=true --no-headers | wc -l
      register: gpu_node_count
      changed_when: false

    - name: Print total number of GPU nodes that will be tainted
      debug:
        msg: "Total GPU nodes with nvidia.com/gpu.present=true label: {{ gpu_node_count.stdout }}"

    - name: List GPU nodes that will be tainted
      shell: |
        oc get nodes -l nvidia.com/gpu.present=true -o jsonpath='{.items[*].metadata.name}'
      register: gpu_node_names
      changed_when: false

    - name: Print GPU node names
      debug:
        msg: "GPU nodes to be tainted: {{ gpu_node_names.stdout.split() }}"
      when: gpu_node_names.stdout != ""

    - name: Taint nodes
      shell: |
        oc adm taint node -l nvidia.com/gpu.present=true nvidia.com/gpu=:NoSchedule --overwrite
        oc adm drain -l nvidia.com/gpu.present=true --ignore-daemonsets --delete-emptydir-data
        oc adm uncordon -l nvidia.com/gpu.present=true-headers
      register: taint_gpu_nodes
      retries: 10
      delay: 10
      until: taint_gpu_nodes.rc == 0
      changed_when: false

    - name: Verify GPU nodes are tainted
      shell: |
        oc get nodes -l nvidia.com/gpu.present=true -o jsonpath='{.items[*].spec.taints}'
      register: gpu_node_taints
      retries: 5
      delay: 5
      until: gpu_node_taints.stdout != ""
      changed_when: false

    - name: Print GPU node taints
      debug:
        msg: "GPU nodes taints: {{ gpu_node_taints.stdout }}"
      when: gpu_node_taints.stdout != ""

    - name: Uncordon all GPU nodes
      shell: |
        for node in $(oc get nodes -l nvidia.com/gpu.present=true -o name | awk -F/ '{print $2}'); do
          oc adm uncordon "$node"
        done
      register: uncordon_gpu_nodes

    - name: Print uncordon result for GPU nodes
      debug:
        msg: "{{ uncordon_gpu_nodes.stdout }}"

    - name: Verify GPU nodes are ready
      shell: |
        oc get nodes -l nvidia.com/gpu.present=true -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
      register: gpu_node_ready
      retries: 5
      delay: 5
      until: gpu_node_ready.stdout == "True"
      changed_when: false

    - name: Print GPU node readiness status
      debug:
        msg: "GPU nodes readiness status: {{ gpu_node_ready.stdout }}"
      when: gpu_node_ready.stdout == "True"
