apiVersion: v1
kind: Secret
metadata:
  name: htpasswd
  namespace: openshift-config
type: Opaque
stringData:
  htpasswd: |
    user1:$2y$05$nnMALtBGonmWOSKkCcojm.QXG8WJp0XwwIrabKmmLycYAeQx.D.UC
    admin1:$2y$05$9rXpvDBDcBHVqRDKIfLzju.iWtgAIzaVsmEBZRGFe16koK7a6ZQzO
    rhoai-user1:$2y$05$tzhA0yPE3WBKVXczeuSD5OkKLcFhdut5X4uhRI9Havqxg0bAfyDNm
    rhoai-admin1:$2y$05$27fvlPdeILT6lP2xUkoTR.EIomrfdUZKEinSXjaTh.oYjGdxopHhO
